### ISSUE TITLE
no installer; 

### ISSUE THREAD

**Issue by chromeplexx** [namazso/SecureUxTheme#192]

**Comment by chromeplexx** [comment]
ok so i installed the latest version of secureuxtheme, but only the warranty popup shows up. i've tried using the older versions, still nothing. i use win10 22h2, my OS build is 19045.4529

**Comment by Asad-13** [comment]
Same here, I don't know what's happening, especially because just a few days earlier I was using it completely fine. Then I uninstalled it, and now when I want to install it again, I don't even get it open? I did delete the old file and downloaded the latest version, but this is nowhere to be mentioned except here.

**Comment by Abhinav2011VS** [comment]
Same Here, I installed it 2 months ago, it was having no problem. But now it is showing Warranty pop-up

**Comment by Asad-13** [comment]
The warranty pop-up is supposed to be showing. But then the application should start too. That's what's missing.

**Comment by Asad-13** [comment]
I just checked on a completely fresh VM install of Windows 10. The same happened: no UI. It's safe to say that the problem is within the application.

**Comment by LossMON** [comment]
> Same issue here, is there any alternative ? [windows 10]

figured it out. you just need to disable core isolation and then it'll work. i was wondering why it wouldnt show anything when i launch it. but turns out it was because of core isolation. disabling it will fix this issue.

**Comment by LossMON** [comment]
> ok so i installed the latest version of secureuxtheme, but only the warranty popup shows up. i've tried using the older versions, still nothing. i use win10 22h2, my OS build is 19045.4529

Disable Core isolation and then restart your pc. That should fix it. idk if this issue is with everyone but i just tried it and it fixed the issue.

**Comment by Asad-13** [comment]
I have it turned off already. It doesn't work for me.

,,,But what if I turn it on? (will update in a few minutes)

**Comment by TrantaLocked** [comment]
Installed Nvidia 560.70, theme broke and can't open ThemeTool, go back to previous driver and still broken.

**Comment by Schleifenkratzer** [comment]
i have the same issue

**Comment by david-UT99** [comment]
hey guys. i finally had to sign up for github to help with this new problem.)

i had build 19045.4651 (july 9th) and the program still worked, i used it a week or 2 ago. it wasn't til after i got the new release preview 19045.4717 late last week that i opened it again and just get the usual copyright or whatever message.
i looked over event viewer and it says "ucrtbase.dll" is part of the error, then i did some searching and it may be related to .net framework. i tried reinstalling/repairing that and all the c++ visual, tried cmd sfc /scannow and DISM /Online /Cleanup-Image /ScanHealth etc, none of that helped. 
i also tried rolling back the preview update i did but of course didn't help. i also have nvidia 560.70, it's not related though because my dad has amd gpu on his computer & the program won't start there either.

i found only 1 thing that works: it opens in safe mode! but you can't see anything cause of all the stuff that's disabled there.

**Comment by amarevite** [comment]
I'm able to run it from Windows Sandbox just fine and get past the warranty popup to the actual interface, but I'm not able to get to the interface on the host machine I'm running the Windows Sandbox on (clicking Ok on the popup closes the program and it's no longer listed in Task Manager). I found that if I attach x32dbg, the program seems to crash when loading in `C:\Windows\SysWOW64\OneCoreUAPCommonProxyStub.dll`, but that's all I can figure out. This issue seems related to (or the same as) #184. I'm running Windows 10 19045.4780 (22H2).

**Comment by roooooooooooooooo** [comment]
reporting same issue: reinstalled win10, cant get beyond the initial warning popup.

**Comment by ToddIndry37** [comment]
> I'm able to run it from Windows Sandbox just fine and get past the warranty popup to the actual interface, but I'm not able to get to the interface on the host machine I'm running the Windows Sandbox on (clicking Ok on the popup closes the program and it's no longer listed in Task Manager). I found that if I attach x32dbg, the program seems to crash when loading in `C:\Windows\SysWOW64\OneCoreUAPCommonProxyStub.dll`, but that's all I can figure out. This issue seems related to (or the same as) #184. I'm running Windows 10 19045.4780 (22H2).

Interesting, so that file is the culprit or something after several cumulative updates on Windows 10? Huh, interesting find though. I wish the author likely to update SecureUxTheme ASAP for Windows 8 or later (including Windows 10) for fix this issue.

**Comment by Anjaneekumar** [comment]
**UPDATE ON ISSUE**

Date: August 23, 2024

Description:

The application crashes when clicking "Ok" on the Warranty page. Additionally, I noticed that the executable file is running as a 32-bit application in Task Manager, which is unexpected.

Here is Windows log (might be useful) for Application: ThemeTool.exe Release v2.2.0

Faulting application name: ThemeTool.exe, version: 0.0.0.0, time stamp: 0x1819ad09
Faulting module name: ucrtbase.dll, version: 10.0.19041.3636, time stamp: 0x6763d3a2
Exception code: 0xc0000409
Fault offset: 0x0009eddb
Faulting process id: 0x1fd8
Faulting application start time: 0x01daf5118a9afa4a
Faulting application path: C:\Users\user\Downloads\themes\ThemeTool.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll

seems like the file "ucrtbase.dll" is causing this issue. Hope will be fixed soon.

**Comment by ToddIndry37** [comment]
Yes, it’s currently well known issue for now. Apparently Microsoft patched that file not long ago or in recent cumulative update that makes SecureUxTheme unusable.

**Comment by amarevite** [comment]
Well this is odd. I upgraded to a new CPU today (AMD→Intel) and had to use the Windows Media Creation Tool to upgrade Windows in place (keeping apps and files) and get everything working smoothly again. I'm now able to use ThemeTool.exe with no issue again. Weirdly, my kernel seems to have downgraded? I was previously running Windows 10 19045.4780 (22H2) as mentioned in my last comment, but now I'm running 19045.3803. I don't know how Windows labels its kernel updates, but 3803 is smaller than 4780 so I think it may be an older version? I have checked for updates and have none available though, so I'm unsure.

**Comment by david-UT99** [comment]
hmm interesting. i was thinking about backing up and starting over since i've had this windows installed since 22.

**Comment by amarevite** [comment]
I've had Windows installed four 5 years according to PC Health Check and at this point I want to see how long I can go without reinstalling Windows. I've put this install through the ringer and it's still chugging along.

To clarify on my last comment, I didn't reinstall Windows or even use a USB to repair. I downloaded MediaCreationTool and it has an option to upgrade without burning to a USB. I'm guessing it's installing Windows on top of itself and affecting everything OS-related, even if it wouldn't usually be touched by a normal update through the settings app.

**Comment by dreadbalaur** [comment]
Is SecureUxTheme still being actively maintained? If not we might have to settle with manual fixes or an alternative program.

**Comment by david-UT99** [comment]
i fresh installed latest stable windows 11 and it's working. only difference (problem) i've encountered is my themes don't change the task manager font color like on 10, and the font is like size 6 while using 120-125 dpi scaling. :(

**Comment by namazso** [comment]
Fixed in 3.0.0
